# Generated by Django 5.1.4 on 2025-01-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
