# Generated by Django 5.1.4 on 2025-01-21 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_generaluser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='profile_pic/')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.generaluser')),
            ],
        ),
    ]
