# Generated by Django 5.1.4 on 2025-01-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userId',
        ),
    ]
