# Generated by Django 5.1.4 on 2025-01-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_remove_userprofile_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='profile_pic/')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.generaluser')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
