# Generated by Django 5.1.4 on 2025-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_userprofileimage_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
