# Generated by Django 5.1.4 on 2025-01-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_alter_generaluser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
