# Generated by Django 5.1.4 on 2025-01-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_alter_generaluser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.generaluser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUserRole',
            fields=[
                ('project_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Team Member', 'Team Member')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.generaluser')),
            ],
        ),
    ]
