# Generated by Django 5.1.4 on 2025-01-26 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_remove_projectuserrole_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
