# Generated by Django 5.1.4 on 2025-01-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_alter_userprofileimage_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
